# Generated by Django 4.0.1 on 2022-01-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('content_id', models.PositiveIntegerField()),
                ('is_like', models.BooleanField(null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('user_id', 'content_id')},
            },
        ),
    ]
